# Generated by Django 5.0.3 on 2024-05-07 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        ('news_image', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsimage',
            name='file',
        ),
        migrations.AddField(
            model_name='newsimage',
            name='file_path',
            field=models.CharField(default='news_images', max_length=255),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_images', to='news.news'),
        ),
    ]
