# Generated by Django 5.0.3 on 2024-05-07 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_content'),
        ('news_image', '0002_remove_newsimage_file_newsimage_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsimage',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_image', to='news.news'),
        ),
    ]
