# Generated by Django 5.0.3 on 2024-05-12 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(help_text='Lütfen JPG, JPEG veya PNG formatında bir resim yükleyin.', upload_to='news_images/{news_category}/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
