# Generated by Django 5.0.3 on 2024-05-12 14:14

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery_option', '0001_initial'),
        ('product_category', '0001_initial'),
        ('unit_of_sale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('seller_first_name', models.CharField(max_length=64)),
                ('seller_last_name', models.CharField(max_length=64)),
                ('seller_contact_no', models.CharField(max_length=10)),
                ('image', models.ImageField(help_text='Lütfen JPG, JPEG veya PNG formatında bir resim yükleyin.', upload_to='product_images/{parent_category}/{subcategory}', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('delivery_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='delivery_option.deliveryoption')),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_products', to='product_category.productcategory')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_products', to='product_category.productcategory')),
                ('unit_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='unit_of_sale.unitofsale')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
                'ordering': ['-created_at'],
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
