# Generated by Django 5.0.3 on 2024-05-26 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minibus',
            name='image',
            field=models.ImageField(help_text='Lütfen JPG, JPEG veya PNG formatında bir resim yükleyin.', upload_to='minibus_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
