# Generated by Django 5.0.3 on 2024-05-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_stop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='departure_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='busstop',
            name='return_time',
            field=models.TimeField(),
        ),
    ]
