# Generated by Django 5.0.3 on 2024-05-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared_car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedcar',
            name='number_of_passengers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
